In [ ]:
pip install numpy

In [ ]:
import numpy as np
array_1d = np.array([1,2,3,4])
print("1D Array:",array_1d)

array_2d = np.array([[1,2],[3,4]])
print("2D Array:\n",array_2d)

result = array_1d + 2
print("Array Addition:", result)
dot_product = np.dot(array_2d,[[1],[1]])
print("dot product:\n",dot_product)
range_array = np.arange(1,10,2)
print(range_array)

linspace_array= np.linspace(0,1,5)
print(linspace_array)

random_integers = np.random.randint(0,100,(3,3))
print(random_integers)

1D Array: [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]]
Array Addition: [3 4 5 6]
dot product:
 [[3]
 [7]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
[[16 64 42]
 [ 1 33 84]
 [49 64 79]]


In [ ]:
# Import NumPy library
import numpy as np

array = np.random.randint(1, 101, size=(4, 5))

print("2D Array:")
print(array)

2D Array:
[[89 99  7 50 82]
 [52  5 96  5 33]
 [44 93 25 75  1]
 [59 58 86 44 32]]


In [ ]:
# Import NumPy library
import numpy as np

# Create a 3D matrix A (2 x 2 x 2)
A = np.array([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]]
])

B = np.array([10, 20])
result = A * B


print("Matrix A:")
print(A)

print("\nArray B:")
print(B)

print("\nResult after broadcasting multiplication:")
print(result)

Matrix A:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Array B:
[10 20]

Result after broadcasting multiplication:
[[[ 10  40]
  [ 30  80]]

 [[ 50 120]
  [ 70 160]]]


In [ ]:
import numpy as np
arr =np.array([10,20,30,40])
std_dev=np.std(arr)
print("standard deviation:",std_dev)


standard deviation: 11.180339887498949


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mean = np.mean(arr)
variance = np.var(arr)
std_dev = np.std(arr)

print("Mean:", mean)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 30.0
Variance: 200.0
Standard Deviation: 14.142135623730951


In [ ]:
pip install pandas


In [ ]:
import pandas as pd
data=[10,20,30,40]
s = pd.Series(data)
print(s)

 #DICTIONARY
data={10:20,30:40}
s=pd.Series(data)
print(s)

s=pd.Series([1,None,31])
print(s.isnull())

0    10
1    20
2    30
3    40
dtype: int64
10    20
30    40
dtype: int64
0    False
1     True
2    False
dtype: bool


In [ ]:
import pandas as pd
data = {
    'Name' : ['Alice','bob','charlie'],
    'age' : [25,30,35],
    'city' : ['newyork','san francisco','los angeles'] }
df=pd.DataFrame(data)
df

,Name,age,city
0,Alice,25,newyork
1,bob,30,san francisco
2,charlie,35,los angeles


In [ ]:
data={
    'Name':['Alice','Bob','Charlie','Diana','Ethan'],
    'Age':[25,30,35,28,40],
    'Department':["IT","Finance",'HR','IT','Operations'],
    'Salary':[50000,60000,55000,62000,58000]}
df=pd.DataFrame(data)
print(df)
print(df.head(3))
print(df.tail(3))
filtered_df=df[df['Age']>30]
print(filtered_df)
grouped=df.groupby("Department")['Salary'].mean()
print(grouped)
sorted_df=df.sort_values(by='Salary',ascending=False)
print(sorted_df)

      Name  Age  Department  Salary
0    Alice   25          IT   50000
1      Bob   30     Finance   60000
2  Charlie   35          HR   55000
3    Diana   28          IT   62000
4    Ethan   40  Operations   58000
      Name  Age Department  Salary
0    Alice   25         IT   50000
1      Bob   30    Finance   60000
2  Charlie   35         HR   55000
      Name  Age  Department  Salary
2  Charlie   35          HR   55000
3    Diana   28          IT   62000
4    Ethan   40  Operations   58000
      Name  Age  Department  Salary
2  Charlie   35          HR   55000
4    Ethan   40  Operations   58000
Department
Finance       60000.0
HR            55000.0
IT            56000.0
Operations    58000.0
Name: Salary, dtype: float64
      Name  Age  Department  Salary
3    Diana   28          IT   62000
1      Bob   30     Finance   60000
4    Ethan   40  Operations   58000
2  Charlie   35          HR   55000
0    Alice   25          IT   50000


In [ ]:
data={
    'Name':['Alice','Bob','Charlie','Diana','Ethan'],
    'Age':[25,30,35,28,40],
    'Department':["IT","Finance",'HR','IT','Operations'],
    'Salary':[50000,60000,55000,62000,58000]}
df=pd.DataFrame(data)
print(df.head(2))
print(df['Salary'].isnull())
print(df['Salary'].isnull().sum())
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
print(df)
df_dropped_rows = df.dropna()
print(df_dropped_rows)
df_dropped_rows = df.dropna(axis =1)
df_dropped_rows
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Salary']=df['Salary'].fillna(df['Salary'].mean)
print(df)
duplicates = df.duplicated()
print(duplicates)
df_no_duplicates=df_

    Name  Age Department  Salary
0  Alice   25         IT   50000
1    Bob   30    Finance   60000
0    False
1    False
2    False
3    False
4    False
Name: Salary, dtype: bool
0
      Name  Age  Department  Salary
0    Alice   25          IT   50000
1      Bob   30     Finance   60000
2  Charlie   35          HR   55000
3    Diana   28          IT   62000
4    Ethan   40  Operations   58000
      Name  Age  Department  Salary
0    Alice   25          IT   50000
1      Bob   30     Finance   60000
2  Charlie   35          HR   55000
3    Diana   28          IT   62000
4    Ethan   40  Operations   58000
      Name  Age  Department  Salary
0    Alice   25          IT   50000
1      Bob   30     Finance   60000
2  Charlie   35          HR   55000
3    Diana   28          IT   62000
4    Ethan   40  Operations   58000


In [ ]:
()

TASK

In [ ]:
import pandas as pd

# Create the data
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 35, 40, 45],
    "Salary": [50000, 60000, 70000, 80000, 90000],
    "Department": ["HR", "Finance", "Tech", "Tech", "HR"],
    "Experience": [2, 5, 8, 10, 12]
}

# Create DataFrame
df = pd.DataFrame(data)

# Filter the DataFrame
filtered_df = df[
    (df["Salary"] > 60000) &
    (df["Experience"] > 5) &
    (df["Department"] == "Tech")
]

# Display only required columns
result = filtered_df[["Name", "Salary", "Experience"]]

print(result)

      Name  Salary  Experience
2  Charlie   70000           8
3    David   80000          10


In [ ]:
import pandas as pd

# Create the DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 35, 40, 45],
    "Salary": [50000, 60000, 70000, 80000, 90000],
    "Department": ["HR", "Finance", "Tech", "Tech", "HR"],
    "Experience": [2, 5, 8, 10, 12]
}

df = pd.DataFrame(data)

# Sort by Department (ascending) and Salary (descending)
sorted_df = df.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
)

# Display the top 5 rows
print(sorted_df.head(5))


      Name  Age  Salary Department  Experience
1      Bob   30   60000    Finance           5
4      Eva   45   90000         HR          12
0    Alice   25   50000         HR           2
3    David   40   80000       Tech          10
2  Charlie   35   70000       Tech           8


In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

titanic_data = pd.read_csv(url)

# Average Fare by Passenger Class
print(titanic_data.groupby('Pclass')['Fare'].mean())

# Maximum Age by Embarked Port
print(titanic_data.groupby('Embarked')['Age'].max())

# Survival Rate by Gender
print(titanic_data.groupby('Sex')['Survived'].mean())

# Survival Rate by Passenger Class
print(titanic_data.groupby('Pclass')['Survived'].mean())

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64
Embarked
C    71.0
Q    70.5
S    80.0
Name: Age, dtype: float64
Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64


TASK

In [2]:
import pandas as pd

# Load Housing Dataset
url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"

housing_data = pd.read_csv(url)

# Count missing values in each column
print("Missing values in each column:")
print(housing_data.isnull().sum())

# Drop rows with missing values
housing_data_clean = housing_data.dropna()

print("\nDataset after dropping missing values:")
print(housing_data_clean.shape)

# Display first 5 rows
print("\nFirst 5 rows of cleaned dataset:")
print(housing_data_clean.head())

Missing values in each column:
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Dataset after dropping missing values:
(20433, 10)

First 5 rows of cleaned dataset:
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1

In [3]:
import pandas as pd

# Load Housing Dataset
url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"

housing_data = pd.read_csv(url)

# Check missing values
print(housing_data.isnull().sum())

# Replace missing values in 'total_bedrooms' with the column mean
housing_data['total_bedrooms'] = housing_data['total_bedrooms'].fillna(
    housing_data['total_bedrooms'].mean()
)

# Verify missing values are replaced
print("\nAfter replacing missing values:")
print(housing_data.isnull().sum())

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

After replacing missing values:
longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64


In [4]:
import pandas as pd

# Load Housing Dataset
url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"

housing_data = pd.read_csv(url)

# Filter rows
filtered_data = housing_data[
    (housing_data['median_income'] > 5) &
    (housing_data['housing_median_age'] > 30)
]

# Display filtered rows
print(filtered_data)

# Number of filtered rows
print("\nNumber of rows:", len(filtered_data))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
61       -122.29     37.82                49.0        135.0            29.0   
110      -122.25     37.82                52.0       1424.0           289.0   
...          ...       ...                 ...          ...             ...   
20217    -119.25     34.28                36.0       2232.0           373.0   
20221    -119.27     34.29                32.0       2274.0           406.0   
20349    -119.08     34.17                32.0        166.0            22.0   
20422    -118.90     34.14                35.0       1503.0           263.0   
20435    -118.64     34.25                47.0       1315.0           290.0   

       population  households  median_income  media

In [5]:
import pandas as pd

# Load Housing Dataset
url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"

housing_data = pd.read_csv(url)

# Compute average house value by ocean proximity
average_house_value = housing_data.groupby('ocean_proximity')['median_house_value'].mean()

print("Average House Value by Ocean Proximity:")
print(average_house_value)

Average House Value by Ocean Proximity:
ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64


In [6]:
import pandas as pd

# Load Housing Dataset
url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"

housing_data = pd.read_csv(url)

# Sort by median_income in descending order
sorted_data = housing_data.sort_values(by='median_income', ascending=False)

# Display top 10 rows
print(sorted_data.head(10))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8851     -118.42     34.09                40.0       3552.0           392.0   
8850     -118.41     34.09                37.0       2716.0           302.0   
8849     -118.40     34.08                52.0       3815.0           439.0   
8848     -118.39     34.08                52.0       3759.0           464.0   
8852     -118.42     34.08                48.0       2413.0           261.0   
15241    -117.23     32.99                17.0       2718.0           326.0   
8878     -118.50     34.04                52.0       3000.0           374.0   
8805     -118.34     33.76                34.0       5586.0           674.0   
8847     -118.40     34.09                45.0       2686.0           283.0   
16910    -122.36     37.56                32.0       4684.0           540.0   

       population  households  median_income  median_house_value  \
8851       1024.0       370.0        15.0001            500001

In [7]:
import pandas as pd

# Load Housing Dataset
url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"

housing_data = pd.read_csv(url)

# Find correlation between median_income and median_house_value
correlation = housing_data['median_income'].corr(
    housing_data['median_house_value']
)

print("Correlation between Median Income and House Value:")
print(correlation)

Correlation between Median Income and House Value:
0.688075207958548
